<script setup lang="ts">
import { Clock3, ListVideo, MessageCircleMore, MonitorUp, Radio, RefreshCw, Settings2, Volume2 } from '@lucide/vue';
import type { ObsStatus } from '../../shared/contracts/obs';
import type { PreparedScriptPlaybackSnapshot } from '../../modules/playback/prepared-script-playback';
import type { ProjectPreparedScript } from '../../shared/contracts/projects';

const props = defineProps<{ obsStatus: ObsStatus; obsBusy: boolean; scripts: ProjectPreparedScript[]; snapshot: PreparedScriptPlaybackSnapshot; }>();
const emit = defineEmits<{ export: []; openPreparedScripts: []; playRole: ['activation' | 'conversation']; playScript: [scriptId: string]; startSequence: []; pause: []; resume: []; skip: []; stop: []; settings: []; start: []; connectObs: []; toggleCamera: []; }>();
const waitingScripts = () => props.scripts.filter((script) => script.role === 'idle');
const priorityScripts = () => props.scripts.filter((script) => script.role === 'activation');
const conversationScripts = () => props.scripts.filter((script) => script.role === 'conversation');
function outputState(): string { if (props.obsStatus.virtualCameraActive) return 'CAM ON'; if (props.obsStatus.browserSourceReady) return 'CONNECTED'; if (props.obsStatus.connected) return 'OBS'; return 'OFFLINE'; }
</script>

<template>
  <section class="studio-mixer-footer">
    <section class="mixer-panel timeline-panel">
      <header class="script-board-heading"><ListVideo :size="15" /><div><span>Kịch bản</span><small>Điều phối video nền, ưu tiên và phản hồi livestream</small></div><button type="button" class="timeline-edit-button" @click="emit('openPreparedScripts')">Chỉnh chi tiết</button></header>
      <div class="timeline-body script-orchestra">
        <section class="script-lane loop-lane"><div class="script-lane-label"><RefreshCw :size="14" /><div><strong>Vòng lặp nền</strong><small>{{ waitingScripts().length }} mục · chạy liên tục</small></div></div><div class="timeline-track"><button v-for="(script, index) in waitingScripts()" :key="script.id" type="button" class="timeline-clip" :class="{ active: snapshot.activeScriptId === script.id, disabled: !script.enabled }" :disabled="!script.enabled" @click="emit('playScript', script.id)"><b>{{ index + 1 }}</b><span>{{ script.name }}</span><small>{{ script.playbackType }}</small></button><small v-if="!waitingScripts().length" class="timeline-empty">Chọn source rồi thêm vào vòng lặp.</small></div><div class="timeline-playback-controls"><button v-if="snapshot.mode === 'stopped' || snapshot.mode === 'error'" type="button" :disabled="!waitingScripts().length" @click="emit('startSequence')">Chạy</button><button v-else-if="snapshot.mode === 'playing'" type="button" @click="emit('pause')">Tạm dừng</button><button v-else-if="snapshot.mode === 'paused'" type="button" @click="emit('resume')">Tiếp tục</button><button type="button" :disabled="!snapshot.activeScriptId" @click="emit('skip')">Bỏ qua</button><button type="button" :disabled="snapshot.mode === 'stopped'" @click="emit('stop')">Dừng</button></div></section>
        <section class="script-lane priority-lane"><div class="script-lane-label"><Clock3 :size="14" /><div><strong>Chờ phát ưu tiên</strong><small>Đợi video nền hiện tại kết thúc</small></div></div><div class="timeline-track"><button v-for="(script, index) in priorityScripts()" :key="script.id" type="button" class="timeline-clip priority-clip" :class="{ active: snapshot.activeScriptId === script.id, disabled: !script.enabled }" :disabled="!script.enabled" @click="emit('playScript', script.id)"><b>{{ index + 1 }}</b><span>{{ script.name }}</span><small>{{ script.playbackType }} · chờ lượt</small></button><small v-if="!priorityScripts().length" class="timeline-empty">Thêm kịch bản kích hoạt trong Chỉnh chi tiết.</small></div><button type="button" class="script-lane-trigger priority-trigger" :disabled="!priorityScripts().length" @click="emit('playRole', 'activation')">Yêu cầu phát</button></section>
        <section class="script-lane conversation-lane"><div class="script-lane-label"><MessageCircleMore :size="14" /><div><strong>Phản hồi tức thời</strong><small>Chào khách · tư vấn · trả lời</small></div></div><div class="timeline-track"><button v-for="(script, index) in conversationScripts()" :key="script.id" type="button" class="timeline-clip conversation-clip" :class="{ active: snapshot.activeScriptId === script.id, disabled: !script.enabled }" :disabled="!script.enabled" @click="emit('playScript', script.id)"><b>{{ index + 1 }}</b><span>{{ script.name }}</span><small>{{ script.playbackType }} · phản hồi</small></button><small v-if="!conversationScripts().length" class="timeline-empty">Thêm câu chào hoặc tư vấn trong Chỉnh chi tiết.</small></div><button type="button" class="script-lane-trigger conversation-trigger" :disabled="!conversationScripts().length" @click="emit('playRole', 'conversation')">Phát phản hồi</button></section>
        <small v-if="snapshot.queuedScriptIds.length" class="timeline-waiting">{{ snapshot.queuedScriptIds.length }} kịch bản đang chờ đến lượt phát.</small><small v-if="snapshot.errorMessage" class="playlist-error">{{ snapshot.errorMessage }}</small>
      </div>
    </section>
    <div class="studio-actions"><section class="livestream-output" :class="{ connected: obsStatus.connected }"><header><Volume2 :size="14" /><span>Đầu ra OBS</span><b>{{ outputState() }}</b></header><small>{{ obsStatus.browserSourceReady ? obsStatus.sourceName : 'Chưa tạo Browser Source' }}</small><div><button v-if="!obsStatus.browserSourceReady" type="button" :disabled="obsBusy" @click="emit('connectObs')">{{ obsBusy ? 'Đang kết nối...' : 'Kết nối OBS' }}</button><button v-else type="button" :disabled="obsBusy || (!obsStatus.virtualCameraAvailable && !obsStatus.virtualCameraActive)" @click="emit('toggleCamera')">{{ obsStatus.virtualCameraActive ? 'Dừng camera' : 'Bật camera' }}</button><button type="button" :disabled="obsBusy" @click="emit('settings')">Cài đặt</button></div></section><button type="button" class="studio-action muted" @click="emit('export')"><MonitorUp :size="15" />Xuất video</button><button type="button" class="studio-action live" @click="emit('start')"><Radio :size="15" />Bắt đầu livestream</button><button type="button" class="studio-action live" @click="emit('settings')"><Settings2 :size="15" />Cài đặt livestream</button></div>
  </section>
</template>
