<script setup lang="ts">
/* global Event, HTMLInputElement */
import { AudioLines, Clock3, ListVideo, MessageCircleMore, MonitorUp, Radio, RefreshCw, Settings2, Volume2, VolumeX } from '@lucide/vue';
import { computed } from 'vue';
import type { ObsStatus } from '../../shared/contracts/obs';
import type { PreparedScriptPlaybackSnapshot } from '../../modules/playback/prepared-script-playback';
import type { ProjectPreparedScript, ProjectSceneLayer } from '../../shared/contracts/projects';

const props = defineProps<{ obsStatus: ObsStatus; obsBusy: boolean; scripts: ProjectPreparedScript[]; snapshot: PreparedScriptPlaybackSnapshot; layers: ProjectSceneLayer[]; activeLayerIndex: number | null; }>();
const emit = defineEmits<{ export: []; openPreparedScripts: []; playRole: ['activation' | 'conversation']; playScript: [scriptId: string]; startSequence: []; pause: []; resume: []; skip: []; stop: []; settings: []; start: []; connectObs: []; toggleCamera: []; selectLayer: [index: number]; setLayerAudio: [layerId: string, muted: boolean, volume: number]; }>();
const waitingScripts = () => props.scripts.filter((script) => script.role === 'idle');
const priorityScripts = () => props.scripts.filter((script) => script.role === 'activation');
const conversationScripts = () => props.scripts.filter((script) => script.role === 'conversation');
const mediaLayers = computed(() => props.layers.filter((layer) => ['video', 'avatar'].includes(layer.kind)));
const activeLayer = computed(() => props.activeLayerIndex === null ? null : props.layers[props.activeLayerIndex] ?? null);
const activeHasAudio = computed(() => Boolean(activeLayer.value && ['video', 'audio', 'avatar'].includes(activeLayer.value.kind)));
function outputState(): string { if (props.obsStatus.virtualCameraActive) return 'CAM ON'; if (props.obsStatus.browserSourceReady) return 'CONNECTED'; if (props.obsStatus.connected) return 'OBS'; return 'OFFLINE'; }
function mediaIndex(layer: ProjectSceneLayer): number { return props.layers.findIndex((candidate) => candidate.id === layer.id); }
function updateVolume(event: Event): void { if (!activeLayer.value) return; emit('setLayerAudio', activeLayer.value.id, activeLayer.value.muted, Number((event.target as HTMLInputElement).value)); }
</script>

<template>
  <section class="studio-mixer-footer">
    <section class="mixer-panel timeline-panel">
      <aside class="script-manager"><header><div><ListVideo :size="15" /><span><strong>Cảnh phát</strong><small>Chọn luồng cần phát</small></span></div><button type="button" class="timeline-edit-button" @click="emit('openPreparedScripts')">Sửa danh sách</button></header><section class="script-manager-row"><RefreshCw :size="14" /><div><strong>Tự chạy nền</strong><small>{{ waitingScripts().length }} clip · quay lại sau khi phát xong</small></div><button type="button" :disabled="!waitingScripts().length" @click="emit('startSequence')">Phát nền</button></section><section class="script-manager-row priority"><Clock3 :size="14" /><div><strong>Phát ưu tiên</strong><small>{{ priorityScripts().length }} cảnh · chèn vào là phát ngay</small></div><button type="button" :disabled="!priorityScripts().length" @click="emit('playRole', 'activation')">Phát kế</button></section><section class="script-manager-row conversation"><MessageCircleMore :size="14" /><div><strong>Thoại trả lời</strong><small>{{ conversationScripts().length }} kịch bản · dùng khi có tương tác</small></div><button type="button" :disabled="!conversationScripts().length" @click="emit('playRole', 'conversation')">Phát thoại</button></section></aside>
      <section class="media-manager"><header class="media-manager-heading"><div><AudioLines :size="15" /><span><strong>Timeline phát</strong><small>Nhấn clip để phát · chọn nguồn để chỉnh tiếng</small></span></div><div class="timeline-playback-controls"><button v-if="snapshot.mode === 'stopped' || snapshot.mode === 'error'" type="button" :disabled="!waitingScripts().length" @click="emit('startSequence')">Phát nền</button><button v-else-if="snapshot.mode === 'playing'" type="button" @click="emit('pause')">Tạm dừng</button><button v-else-if="snapshot.mode === 'paused'" type="button" @click="emit('resume')">Tiếp tục</button><button type="button" :disabled="!snapshot.activeScriptId" @click="emit('skip')">Bỏ qua</button><button type="button" :disabled="snapshot.mode === 'stopped'" @click="emit('stop')">Dừng</button></div></header><div class="media-manager-body"><nav class="media-source-rail" aria-label="Nguồn video có thể phát"><button v-for="layer in mediaLayers" :key="layer.id" type="button" :class="{ active: activeLayer?.id === layer.id }" @click="emit('selectLayer', mediaIndex(layer))"><ListVideo :size="14" /><span>{{ layer.name }}</span></button><small v-if="!mediaLayers.length">Thêm video từ Nguồn rồi tạo cảnh phát.</small></nav><section class="media-timeline-track"><div class="media-timeline-label"><span>LUỒNG TỰ CHẠY</span><small>{{ waitingScripts().length }} clip · nhấn clip để phát từ đầu</small></div><div class="timeline-track"><button v-for="(script, index) in waitingScripts()" :key="script.id" type="button" class="timeline-clip" :class="{ active: snapshot.activeScriptId === script.id, disabled: !script.enabled }" :disabled="!script.enabled" :aria-label="`Phát clip ${index + 1}: ${script.name}`" @click="emit('playScript', script.id)"><b>CLIP {{ String(index + 1).padStart(2, '0') }}</b><span>{{ script.name }}</span><small>{{ script.playbackType === 'tts' ? 'THOẠI' : 'VIDEO' }} · nhấn để phát</small></button><small v-if="!waitingScripts().length" class="timeline-empty">Chọn video ở Nguồn, sau đó thêm vào Tự chạy nền.</small></div></section></div><footer v-if="activeHasAudio && activeLayer" class="active-audio-console"><div><strong>{{ activeLayer.name }}</strong><small>{{ activeLayer.kind === 'video' ? 'Âm thanh gốc video đang chọn' : 'Âm thanh source đang chọn' }}</small></div><button type="button" :aria-label="activeLayer.muted ? 'Bật tiếng' : 'Tắt tiếng'" :aria-pressed="activeLayer.muted" @click="emit('setLayerAudio', activeLayer.id, !activeLayer.muted, activeLayer.volume)"><VolumeX v-if="activeLayer.muted" :size="14" /><Volume2 v-else :size="14" />{{ activeLayer.muted ? 'Bật tiếng' : 'Tắt tiếng' }}</button><label>Âm lượng <b>{{ Math.round(activeLayer.volume * 100) }}%</b><input type="range" min="0" max="1" step="0.05" :value="activeLayer.volume" @input="updateVolume" /></label></footer><small v-if="snapshot.errorMessage" class="playlist-error">{{ snapshot.errorMessage }}</small></section>
    </section>
    <div class="studio-actions"><section class="livestream-output" :class="{ connected: obsStatus.connected }"><header><Volume2 :size="14" /><span>Đầu ra OBS</span><b>{{ outputState() }}</b></header><small>{{ obsStatus.browserSourceReady ? obsStatus.sourceName : 'Chưa tạo Browser Source' }}</small><div><button v-if="!obsStatus.browserSourceReady" type="button" :disabled="obsBusy" @click="emit('connectObs')">{{ obsBusy ? 'Đang kết nối...' : 'Kết nối OBS' }}</button><button v-else type="button" :disabled="obsBusy || (!obsStatus.virtualCameraAvailable && !obsStatus.virtualCameraActive)" @click="emit('toggleCamera')">{{ obsStatus.virtualCameraActive ? 'Dừng camera' : 'Bật camera' }}</button><button type="button" :disabled="obsBusy" @click="emit('settings')">Cài đặt</button></div></section><button type="button" class="studio-action muted" @click="emit('export')"><MonitorUp :size="15" />Xuất video</button><button type="button" class="studio-action live" @click="emit('start')"><Radio :size="15" />Bắt đầu livestream</button><button type="button" class="studio-action live" @click="emit('settings')"><Settings2 :size="15" />Cài đặt livestream</button></div>
  </section>
</template>
